name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4️⃣ Build project
      - name: Build with Gradle
        run: ./gradlew clean build

      # 5️⃣ Run unit tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # 6️⃣ (Optional) Generate APK
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      # 7️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: WhatsappClone-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

